from django.urls import path
from sale import views
urlpatterns = [
    path('',views.index),
    path('admin',views.admin),
    path('index',views.index),
    path('adminhome',views.adminhome),
    path('staff',views.staff),
    path('client',views.client),
    path('category',views.category),
    path('subcategory',views.subcategory),
    path('addclient',views.addclient),
    path('addcustomer',views.addcustomer),
    path('stock',views.stock),
    path('customer',views.customer),
    path('addstaff',views.addstaff),
    path('staffhome',views.staffhome),
    path('currentstock',views.currentstock),
    path('customerhome',views.customerhome),
    path('updatestock',views.updatestock),
    path('emptystock',views.emptystock),
    path('checkout',views.checkout),
    path('addstock',views.addstock),
    path('saleassign',views.saleassign),
    path('target',views.target),
    path('billing1',views.billing1),
    path('bill1',views.bill1),
    path('billing2',views.billing2),
    path('bill2',views.bill2),
    path('sale',views.sale),
    path('details',views.details),
    path('topcustomer',views.topcustomer),
    path('clientpayment',views.clientpayment),
    path('mypurchase',views.mypurchase),
        ]
